services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
      - minio
    networks:
      - app_network
      - minio_network
  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_INTERNAL_API_URL=${NEXT_PUBLIC_INTERNAL_API_URL}
        - NEXT_PUBLIC_S3_STORAGE_URL=${NEXT_PUBLIC_S3_STORAGE_URL}
        - NEXT_PUBLIC_APP_MODE=${NEXT_PUBLIC_APP_MODE}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app_network
      - minio_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      args:
        - SERVER__HOST=localhost
        - SERVER__PORT=8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      api-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./backend/alembic:/app/alembic
    networks:
      - app_network
      - db_network
      - redis_network
      - minio_network
      - elasticsearch_network
      - recsys-network

  api-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=food_social_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db_network

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redis_network

  elasticsearch:
    image: bitnami/elasticsearch:9.0.1

    environment:
      - discovery.type=single-node
      - security.enabled=true
      - ELASTICSEARCH_PASSWORD=${API__ELASTICSEARCH__PASSWORD:-changeme}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch_assets/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch_assets/analysis:/opt/bitnami/elasticsearch/config/analysis
      - elasticsearch_data:/bitnami/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - elasticsearch_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${API__S3_STORAGE__ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${API__S3_STORAGE__SECRET_KEY}
    command: minio server --console-address ':9001' /data &
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - minio_network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 $API__S3_STORAGE__ACCESS_KEY $API__S3_STORAGE__SECRET_KEY;
      mc mb myminio/images;

      exit 0;
      "
    env_file:
      - .env
    networks:
      - minio_network


  qdrant:
    image: qdrant/qdrant:latest
    container_name: recsys-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - recsys-network

  nats:
    image: nats:2.10-alpine
    container_name: recsys-nats
    command: ["nats-server", "--config", "/etc/nats/nats.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"  # HTTP monitoring port
    volumes:
      - nats_data:/data
      - ./nats.conf:/etc/nats/nats.conf:ro
    networks:
      - recsys-network


  recsys-db:
    image: postgres:15
    container_name: recsys-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recsys_db
    volumes:
      - recsys_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recsys-network

  recsys-worker:
    build:
      context: ./recsys
      dockerfile: Dockerfile
    container_name: recsys-worker
    env_file:
      - .env
    ports:
      - "8001:8001"  # Interactive faststream documentation
    depends_on:
      recsys-db:
        condition: service_healthy
      qdrant:
        condition: service_started
      nats:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./recsys/asyncapi_docs:/app/asyncapi_docs
      - ./recsys/alembic:/app/alembic
    networks:
      - recsys-network


networks:
  db_network:
    driver: bridge
  redis_network:
    driver: bridge
  minio_network:
    driver: bridge
  app_network:
    driver: bridge
  elasticsearch_network:
    driver: bridge
  recsys-network:
    driver: bridge

volumes:
  alembic_data:
  postgres_data:
  redis_data:
  minio_data:
  elasticsearch_data:
  qdrant_data:
  nats_data:
  recsys_db_data:
